name: Build and Push Docker images
on:
  workflow_dispatch:
    
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.amd64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/amd64-hass-deepstack:latest

      - name: Build and push aarch64 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.aarch64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/aarch64-hass-deepstack:latest


